import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  static const String _languageKey = 'app_language';
  static const String defaultLocale = 'zh_TW';

  Locale _currentLocale = const Locale('zh', 'TW');
  String _currentLanguageTag = defaultLocale;

  Locale get currentLocale => _currentLocale;
  String get currentLanguageCode => _currentLocale.languageCode;
  String get currentLanguageTag => _currentLanguageTag;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguage = prefs.getString(_languageKey) ?? defaultLocale;
    _setLocale(savedLanguage);
  }

  Future<void> setLanguage(String languageTag) async {
    _setLocale(languageTag);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageTag);
    notifyListeners();
  }

  void _setLocale(String languageTag) {
    _currentLanguageTag = languageTag;
    final parts = languageTag.split('_');
    if (parts.length >= 2) {
      _currentLocale = Locale(parts[0], parts[1]);
    } else {
      _currentLocale = Locale(parts[0]);
    }
  }

  String t(String key) {
    final translations = _translations[_currentLanguageTag] ?? _translations[defaultLocale]!;
    return translations[key] ?? key;
  }

  static String getLanguageName(String languageTag) {
    switch (languageTag) {
      case 'zh_TW': return '繁體中文';
      case 'zh_CN': return '简体中文';
      case 'en_US': return 'English';
      case 'fr_FR': return 'Français';
      case 'es_ES': return 'Español';
      case 'ru_RU': return 'Русский';
      case 'ar_SA': return 'العربية';
      default: return languageTag;
    }
  }

  static List<Map<String, String>> getSupportedLanguages() {
    return [
      {'tag': 'zh_TW', 'name': '繁體中文', 'native': '繁體中文', 'flag': '🇭🇰'},
      {'tag': 'zh_CN', 'name': '简体中文', 'native': '简体中文', 'flag': '🇨🇳'},
      {'tag': 'en_US', 'name': 'English', 'native': 'English', 'flag': '🇺🇸'},
      {'tag': 'fr_FR', 'name': 'French', 'native': 'Français', 'flag': '🇫🇷'},
      {'tag': 'es_ES', 'name': 'Spanish', 'native': 'Español', 'flag': '🇪🇸'},
      {'tag': 'ru_RU', 'name': 'Russian', 'native': 'Русский', 'flag': '🇷🇺'},
      {'tag': 'ar_SA', 'name': 'Arabic', 'native': 'العربية', 'flag': '🇸🇦'},
    ];
  }

  static bool isLanguageEnabled(String languageTag) {
    final enabledLanguages = [
      'zh_TW', 'zh_CN', 'en_US', 'fr_FR', 'es_ES', 'ru_RU', 'ar_SA'
    ];
    return enabledLanguages.contains(languageTag);
  }

  static bool isRTL(String languageTag) {
    return languageTag == 'ar_SA';
  }

  static TextDirection getTextDirection(String languageTag) {
    return isRTL(languageTag) ? TextDirection.rtl : TextDirection.ltr;
  }

  final Map<String, Map<String, String>> _translations = {
    'zh_TW': {
      'app_name': '靈積學堂',
      'platform_slogan': '弘揚傳統文化 · 傳承國學智慧',
      'platform_description': '中國傳統文化學術交流平台',
      'home': '首頁',
      'tcm': '中醫',
      'acupuncture': '針灸',
      'fortune': '命理',
      'wuyun': '五運六氣',
      'blog': '博客',
      'store': '商城',
      'promotion': '推廣',
      'community': '社群',
      'my': '我的',
      'login': '登入',
      'register': '註冊',
      'logout': '登出',
      'member': '會員',
      'settings': '設定',
      'profile': '個人資料',
      'wallet': '錢包',
      'lingji_balance': '靈積餘額',
      'member_level': '會員等級',
      'free_member': '免費會員',
      'basic_member': '初級會員',
      'standard_member': '中級會員',
      'premium_member': '高級會員',
      'ultimate_member': '至尊會員',
      'gold_member': '金牌會員',
      'verification': '認證',
      'email_verification': '郵箱認證',
      'phone_verification': '手機認證',
      'face_verification': '人臉認證',
      'verified': '已認證',
      'not_verified': '未認證',
      'change_password': '更改密碼',
      'disclaimer': '免責聲明',
      'payment_info': '支持微信支付、支付寶，由香港正規企業資質申請海外商戶通道',
      'settlement_info': '資金結算留存香港賬戶',
      'promotion_rules': '零門檻免費註冊即可參與推廣',
      'level1_commission': '一級佣金',
      'level2_commission': '二級佣金',
      'talent_showcase': '達人櫥窗',
      'affiliate_center': '推廣中心',
      'share_link': '推廣鏈接',
      'qr_code': '二維碼',
      'server_region': '香港',
      'payment': '支付',
      'payment_method': '支付方式',
      'recharge': '充值',
      'withdraw': '提現',
      'order_history': '訂單歷史',
      'language': '語言',
      'select_language': '選擇語言',
      'confirm': '確認',
      'cancel': '取消',
      'save': '保存',
      'edit': '編輯',
      'delete': '刪除',
      'search': '搜索',
      'loading': '加載中',
      'error': '錯誤',
      'success': '成功',
      'warning': '警告',
      'info': '信息',
      'yes': '是',
      'no': '否',
      'ok': '確定',
      'back': '返回',
      'next': '下一步',
      'previous': '上一步',
      'submit': '提交',
      'reset': '重置',
      'close': '關閉',
      'open': '打開',
      'enable': '開啟',
      'disable': '關閉',
      'enabled': '已開啟',
      'disabled': '已關閉',
      'all': '全部',
      'none': '無',
      'required': '必填',
      'optional': '選填',
      'username': '用戶名',
      'password': '密碼',
      'email': '郵箱',
      'phone': '手機',
      'captcha': '驗證碼',
      'send_code': '發送驗證碼',
      'balance': '餘額',
      'total': '合計',
      'subtotal': '小計',
      'discount': '折扣',
      'tax': '稅費',
      'fee': '費用',
      'commission': '佣金',
      'settlement': '結算',
      'transaction': '交易',
      'amount': '金額',
      'currency': '貨幣',
      'status': '狀態',
      'pending': '待處理',
      'processing': '處理中',
      'completed': '已完成',
      'failed': '失敗',
      'refunded': '已退款',
      'cancelled': '已取消',
      'expired': '已過期',
      'active': '活躍',
      'inactive': '未激活',
      'locked': '已鎖定',
      'unlocked': '已解鎖',
      'verified': '已驗證',
      'unverified': '未驗證',
      'bind': '綁定',
      'unbind': '解綁',
      'upgrade': '升級',
      'downgrade': '降級',
      'renew': '續費',
      'expire': '過期',
      'vip': 'VIP',
      'premium': '高級',
      'free': '免費',
      'paid': '付費',
      'trial': '試用',
      'new': '新規',
      'hot': '熱門',
      'recommend': '推薦',
      'popular': '人氣',
      'latest': '最新',
      'oldest': '最舊',
      'price': '價格',
      'quantity': '數量',
      'total_price': '總價',
      'unit_price': '單價',
      'description': '描述',
      'content': '內容',
      'title': '標題',
      'summary': '摘要',
      'detail': '詳情',
      'category': '分類',
      'tag': '標籤',
      'type': '類型',
      'date': '日期',
      'time': '時間',
      'duration': '時長',
      'created_at': '創建時間',
      'updated_at': '更新時間',
      'expired_at': '過期時間',
      'view': '查看',
      'browse': '瀏覽',
      'read': '閱讀',
      'write': '寫入',
      'share': '分享',
      'download': '下載',
      'upload': '上傳',
      'export': '導出',
      'import': '導入',
      'sync': '同步',
      'refresh': '刷新',
      'update': '更新',
      'delete_confirm': '確定要刪除嗎？',
      'save_success': '保存成功',
      'save_failed': '保存失敗',
      'operation_success': '操作成功',
      'operation_failed': '操作失敗',
      'network_error': '網絡錯誤',
      'system_error': '系統錯誤',
      'permission_denied': '權限不足',
      'session_expired': '會話已過期',
      'please_login': '請先登入',
      'copyright': '版權所有',
      'terms_of_service': '服務條款',
      'privacy_policy': '隱私政策',
      'contact_us': '聯繫我們',
      'about_us': '關於我們',
      'help_center': '幫助中心',
      'faq': '常見問題',
      'feedback': '意見反饋',
      'report': '舉報',
      'intelligent_acupuncture': '智能辨證配針',
      'select_symptoms': '選擇症狀',
      'select_body_region': '選擇不適部位',
      'tongue_diagnosis': '舌象',
      'pulse_diagnosis': '脈象',
      'diagnosis_result': '辨證結果',
      'treatment_principle': '治療原則',
      'treatment_strategy': '治療策略',
      'prescription': '配針方案',
      'main_points': '主穴',
      'paired_points': '配穴',
      'dong_points': '董氏奇穴',
      'nihaixia_points': '倪海厦特效穴',
      'traditional_points': '傳統經穴',
      'needle_depth': '進針深度',
      'needle_angle': '進針角度',
      'manipulation': '操作手法',
      'reinforcement_reduction': '補瀉',
      'indication': '主治',
      'location': '定位',
      'contraindication': '禁忌',
      'operation_notes': '操作要點',
      'acupoint_source': '穴位來源',
      'source_reference': '來源參考',
      'clinical_note': '臨床備註',
      'prescription_principle': '選穴原理',
      'body_layers': '顯示層次',
      'all_layers': '全部',
      'bone_layer': '骨骼',
      'muscle_layer': '肌肉',
      'meridian_layer': '經絡',
    },
    'zh_CN': {
      'app_name': '灵积学堂',
      'platform_slogan': '弘扬传统文化 · 传承国学智慧',
      'platform_description': '中国传统文化学术交流平台',
      'home': '首页',
      'tcm': '中医',
      'acupuncture': '针灸',
      'fortune': '命理',
      'wuyun': '五运六气',
      'blog': '博客',
      'store': '商城',
      'promotion': '推广',
      'community': '社群',
      'my': '我的',
      'login': '登录',
      'register': '注册',
      'logout': '退出',
      'member': '会员',
      'settings': '设置',
      'profile': '个人资料',
      'wallet': '钱包',
      'lingji_balance': '灵积余额',
      'member_level': '会员等级',
      'free_member': '免费会员',
      'basic_member': '初级会员',
      'standard_member': '中级会员',
      'premium_member': '高级会员',
      'ultimate_member': '至尊会员',
      'gold_member': '金牌会员',
      'verification': '认证',
      'email_verification': '邮箱认证',
      'phone_verification': '手机认证',
      'face_verification': '人脸认证',
      'verified': '已认证',
      'not_verified': '未认证',
      'change_password': '更改密码',
      'disclaimer': '免责声明',
      'payment_info': '支持微信支付、支付宝，由香港正规企业资质申请海外商户通道',
      'settlement_info': '资金结算留存香港账户',
      'promotion_rules': '零门槛免费注册即可参与推广',
      'level1_commission': '一级佣金',
      'level2_commission': '二级佣金',
      'talent_showcase': '达人橱窗',
      'affiliate_center': '推广中心',
      'share_link': '推广链接',
      'qr_code': '二维码',
      'server_region': '香港',
      'payment': '支付',
      'payment_method': '支付方式',
      'recharge': '充值',
      'withdraw': '提现',
      'order_history': '订单历史',
      'language': '语言',
      'select_language': '选择语言',
      'confirm': '确认',
      'cancel': '取消',
      'save': '保存',
      'edit': '编辑',
      'delete': '删除',
      'search': '搜索',
      'loading': '加载中',
      'error': '错误',
      'success': '成功',
      'warning': '警告',
      'info': '信息',
      'yes': '是',
      'no': '否',
      'ok': '确定',
      'back': '返回',
      'next': '下一步',
      'previous': '上一步',
      'submit': '提交',
      'reset': '重置',
      'close': '关闭',
      'open': '打开',
      'enable': '开启',
      'disable': '关闭',
      'enabled': '已开启',
      'disabled': '已关闭',
      'all': '全部',
      'none': '无',
      'required': '必填',
      'optional': '选填',
      'username': '用户名',
      'password': '密码',
      'email': '邮箱',
      'phone': '手机',
      'captcha': '验证码',
      'send_code': '发送验证码',
      'balance': '余额',
      'total': '合计',
      'subtotal': '小计',
      'discount': '折扣',
      'tax': '税费',
      'fee': '费用',
      'commission': '佣金',
      'settlement': '结算',
      'transaction': '交易',
      'amount': '金额',
      'currency': '货币',
      'status': '状态',
      'pending': '待处理',
      'processing': '处理中',
      'completed': '已完成',
      'failed': '失败',
      'refunded': '已退款',
      'cancelled': '已取消',
      'expired': '已过期',
      'active': '活跃',
      'inactive': '未激活',
      'locked': '已锁定',
      'unlocked': '已解锁',
      'verified': '已验证',
      'unverified': '未验证',
      'bind': '绑定',
      'unbind': '解绑',
      'upgrade': '升级',
      'downgrade': '降级',
      'renew': '续费',
      'expire': '过期',
      'vip': 'VIP',
      'premium': '高级',
      'free': '免费',
      'paid': '付费',
      'trial': '试用',
      'new': '新规',
      'hot': '热门',
      'recommend': '推荐',
      'popular': '人气',
      'latest': '最新',
      'oldest': '最旧',
      'price': '价格',
      'quantity': '数量',
      'total_price': '总价',
      'unit_price': '单价',
      'description': '描述',
      'content': '内容',
      'title': '标题',
      'summary': '摘要',
      'detail': '详情',
      'category': '分类',
      'tag': '标签',
      'type': '类型',
      'date': '日期',
      'time': '时间',
      'duration': '时长',
      'created_at': '创建时间',
      'updated_at': '更新时间',
      'expired_at': '过期时间',
      'view': '查看',
      'browse': '浏览',
      'read': '阅读',
      'write': '写入',
      'share': '分享',
      'download': '下载',
      'upload': '上传',
      'export': '导出',
      'import': '导入',
      'sync': '同步',
      'refresh': '刷新',
      'update': '更新',
      'delete_confirm': '确定要删除吗？',
      'save_success': '保存成功',
      'save_failed': '保存失败',
      'operation_success': '操作成功',
      'operation_failed': '操作失败',
      'network_error': '网络错误',
      'system_error': '系统错误',
      'permission_denied': '权限不足',
      'session_expired': '会话已过期',
      'please_login': '请先登录',
      'copyright': '版权所有',
      'terms_of_service': '服务条款',
      'privacy_policy': '隐私政策',
      'contact_us': '联系我们',
      'about_us': '关于我们',
      'help_center': '帮助中心',
      'faq': '常见问题',
      'feedback': '意见反馈',
      'report': '举报',
      'intelligent_acupuncture': '智能辨证配针',
      'select_symptoms': '选择症状',
      'select_body_region': '选择不适部位',
      'tongue_diagnosis': '舌象',
      'pulse_diagnosis': '脉象',
      'diagnosis_result': '辨证结果',
      'treatment_principle': '治疗原则',
      'treatment_strategy': '治疗策略',
      'prescription': '配针方案',
      'main_points': '主穴',
      'paired_points': '配穴',
      'dong_points': '董氏奇穴',
      'nihaixia_points': '倪海厦特效穴',
      'traditional_points': '传统经穴',
      'needle_depth': '进针深度',
      'needle_angle': '进针角度',
      'manipulation': '操作手法',
      'reinforcement_reduction': '补泻',
      'indication': '主治',
      'location': '定位',
      'contraindication': '禁忌',
      'operation_notes': '操作要点',
      'acupoint_source': '穴位来源',
      'source_reference': '来源参考',
      'clinical_note': '临床备注',
      'prescription_principle': '选穴原理',
      'body_layers': '显示层次',
      'all_layers': '全部',
      'bone_layer': '骨骼',
      'muscle_layer': '肌肉',
      'meridian_layer': '经络',
    },
    'en_US': {
      'app_name': 'Lingji Academy',
      'platform_slogan': 'Promoting Traditional Culture · Inheriting National Wisdom',
      'platform_description': 'Traditional Chinese Culture Academic Exchange Platform',
      'home': 'Home',
      'tcm': 'TCM',
      'acupuncture': 'Acupuncture',
      'fortune': 'Fortune',
      'wuyun': 'Wu Yun',
      'blog': 'Blog',
      'store': 'Store',
      'promotion': 'Promotion',
      'community': 'Community',
      'my': 'My',
      'login': 'Login',
      'register': 'Register',
      'logout': 'Logout',
      'member': 'Member',
      'settings': 'Settings',
      'profile': 'Profile',
      'wallet': 'Wallet',
      'lingji_balance': 'Lingji Balance',
      'member_level': 'Member Level',
      'free_member': 'Free Member',
      'basic_member': 'Basic Member',
      'standard_member': 'Standard Member',
      'premium_member': 'Premium Member',
      'ultimate_member': 'Ultimate Member',
      'gold_member': 'Gold Member',
      'verification': 'Verification',
      'email_verification': 'Email Verification',
      'phone_verification': 'Phone Verification',
      'face_verification': 'Face Verification',
      'verified': 'Verified',
      'not_verified': 'Not Verified',
      'change_password': 'Change Password',
      'disclaimer': 'Disclaimer',
      'payment_info': 'WeChat Pay and Alipay supported, applied through Hong Kong enterprise qualifications.',
      'settlement_info': 'Funds are settled and retained in Hong Kong accounts.',
      'promotion_rules': 'Zero threshold, free registration to participate in promotion.',
      'level1_commission': 'Level 1 Commission',
      'level2_commission': 'Level 2 Commission',
      'talent_showcase': 'Talent Showcase',
      'affiliate_center': 'Affiliate Center',
      'share_link': 'Share Link',
      'qr_code': 'QR Code',
      'server_region': 'Hong Kong',
      'payment': 'Payment',
      'payment_method': 'Payment Method',
      'recharge': 'Recharge',
      'withdraw': 'Withdraw',
      'order_history': 'Order History',
      'language': 'Language',
      'select_language': 'Select Language',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'search': 'Search',
      'loading': 'Loading',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Info',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'submit': 'Submit',
      'reset': 'Reset',
      'close': 'Close',
      'open': 'Open',
      'enable': 'Enable',
      'disable': 'Disable',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'all': 'All',
      'none': 'None',
      'required': 'Required',
      'optional': 'Optional',
      'username': 'Username',
      'password': 'Password',
      'email': 'Email',
      'phone': 'Phone',
      'captcha': 'Captcha',
      'send_code': 'Send Code',
      'balance': 'Balance',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'fee': 'Fee',
      'commission': 'Commission',
      'settlement': 'Settlement',
      'transaction': 'Transaction',
      'amount': 'Amount',
      'currency': 'Currency',
      'status': 'Status',
      'pending': 'Pending',
      'processing': 'Processing',
      'completed': 'Completed',
      'failed': 'Failed',
      'refunded': 'Refunded',
      'cancelled': 'Cancelled',
      'expired': 'Expired',
      'active': 'Active',
      'inactive': 'Inactive',
      'locked': 'Locked',
      'unlocked': 'Unlocked',
      'verified': 'Verified',
      'unverified': 'Unverified',
      'bind': 'Bind',
      'unbind': 'Unbind',
      'upgrade': 'Upgrade',
      'downgrade': 'Downgrade',
      'renew': 'Renew',
      'expire': 'Expire',
      'vip': 'VIP',
      'premium': 'Premium',
      'free': 'Free',
      'paid': 'Paid',
      'trial': 'Trial',
      'new': 'New',
      'hot': 'Hot',
      'recommend': 'Recommend',
      'popular': 'Popular',
      'latest': 'Latest',
      'oldest': 'Oldest',
      'price': 'Price',
      'quantity': 'Quantity',
      'total_price': 'Total Price',
      'unit_price': 'Unit Price',
      'description': 'Description',
      'content': 'Content',
      'title': 'Title',
      'summary': 'Summary',
      'detail': 'Detail',
      'category': 'Category',
      'tag': 'Tag',
      'type': 'Type',
      'date': 'Date',
      'time': 'Time',
      'duration': 'Duration',
      'created_at': 'Created At',
      'updated_at': 'Updated At',
      'expired_at': 'Expired At',
      'view': 'View',
      'browse': 'Browse',
      'read': 'Read',
      'write': 'Write',
      'share': 'Share',
      'download': 'Download',
      'upload': 'Upload',
      'export': 'Export',
      'import': 'Import',
      'sync': 'Sync',
      'refresh': 'Refresh',
      'update': 'Update',
      'delete_confirm': 'Are you sure to delete?',
      'save_success': 'Saved Successfully',
      'save_failed': 'Save Failed',
      'operation_success': 'Operation Successful',
      'operation_failed': 'Operation Failed',
      'network_error': 'Network Error',
      'system_error': 'System Error',
      'permission_denied': 'Permission Denied',
      'session_expired': 'Session Expired',
      'please_login': 'Please Login First',
      'copyright': 'Copyright',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',
      'contact_us': 'Contact Us',
      'about_us': 'About Us',
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'feedback': 'Feedback',
      'report': 'Report',
      'intelligent_acupuncture': 'Intelligent Acupuncture',
      'select_symptoms': 'Select Symptoms',
      'select_body_region': 'Select Affected Area',
      'tongue_diagnosis': 'Tongue Diagnosis',
      'pulse_diagnosis': 'Pulse Diagnosis',
      'diagnosis_result': 'Diagnosis Result',
      'treatment_principle': 'Treatment Principle',
      'treatment_strategy': 'Treatment Strategy',
      'prescription': 'Prescription',
      'main_points': 'Main Points',
      'paired_points': 'Paired Points',
      'dong_points': 'Dong Extraordinary Points',
      'nihaixia_points': 'Ni Haixia Special Points',
      'traditional_points': 'Traditional Meridians',
      'needle_depth': 'Needle Depth',
      'needle_angle': 'Needle Angle',
      'manipulation': 'Manipulation',
      'reinforcement_reduction': 'Tonifying/Draining',
      'indication': 'Indication',
      'location': 'Location',
      'contraindication': 'Contraindication',
      'operation_notes': 'Operation Notes',
      'acupoint_source': 'Point Source',
      'source_reference': 'Source Reference',
      'clinical_note': 'Clinical Note',
      'prescription_principle': 'Selection Principle',
      'body_layers': 'Display Layers',
      'all_layers': 'All',
      'bone_layer': 'Bone',
      'muscle_layer': 'Muscle',
      'meridian_layer': 'Meridian',
    },
      'app_name': 'Académie Lingji',
      'platform_slogan': 'Promouvoir la Culture Traditionnelle · Hériter de la Sagesse Nationale',
      'platform_description': 'Plateforme d\'Échange Académique de Culture Traditionnelle Chinoise',
      'home': 'Accueil',
      'tcm': 'Médecine Chinoise',
      'acupuncture': 'Acupuncture',
      'fortune': 'Destin',
      'wuyun': 'Wu Yun',
      'blog': 'Blog',
      'store': 'Boutique',
      'promotion': 'Promotion',
      'community': 'Communauté',
      'my': 'Mon',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'logout': 'Déconnexion',
      'member': 'Membre',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'wallet': 'Portefeuille',
      'lingji_balance': 'Solde Lingji',
      'member_level': 'Niveau de Membre',
      'free_member': 'Membre Gratuit',
      'basic_member': 'Membre Basique',
      'standard_member': 'Membre Standard',
      'premium_member': 'Membre Premium',
      'ultimate_member': 'Membre Ultime',
      'gold_member': 'Membre Or',
      'verification': 'Vérification',
      'email_verification': 'Vérification Email',
      'phone_verification': 'Vérification Téléphone',
      'face_verification': 'Vérification Visage',
      'verified': 'Vérifié',
      'not_verified': 'Non Vérifié',
      'change_password': 'Changer le Mot de Passe',
      'disclaimer': 'Clause de Non-Responsabilité',
      'payment_info': 'WeChat Pay et Alipay pris en charge',
      'settlement_info': 'Fonds réglés et conservés à Hong Kong',
      'promotion_rules': 'Inscription gratuite, commission sur transactions réelles',
      'level1_commission': 'Commission Niveau 1',
      'level2_commission': 'Commission Niveau 2',
      'talent_showcase': 'Vitrine Talents',
      'affiliate_center': 'Centre d\'Affiliation',
      'share_link': 'Lien de Partage',
      'qr_code': 'Code QR',
      'server_region': 'Hong Kong',
      'payment': 'Paiement',
      'payment_method': 'Mode de Paiement',
      'recharge': 'Recharge',
      'withdraw': 'Retrait',
      'order_history': 'Historique des Commandes',
      'language': 'Langue',
      'select_language': 'Sélectionner la Langue',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'search': 'Rechercher',
      'loading': 'Chargement',
      'error': 'Erreur',
      'success': 'Succès',
      'warning': 'Avertissement',
      'info': 'Info',
      'yes': 'Oui',
      'no': 'Non',
      'ok': 'OK',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'submit': 'Soumettre',
      'reset': 'Réinitialiser',
      'close': 'Fermer',
      'open': 'Ouvrir',
      'enable': 'Activer',
      'disable': 'Désactiver',
      'enabled': 'Activé',
      'disabled': 'Désactivé',
      'all': 'Tout',
      'none': 'Aucun',
      'required': 'Requis',
      'optional': 'Optionnel',
      'username': 'Nom d\'utilisateur',
      'password': 'Mot de passe',
      'email': 'Email',
      'phone': 'Téléphone',
      'captcha': 'Captcha',
      'send_code': 'Envoyer le Code',
      'balance': 'Solde',
      'total': 'Total',
      'subtotal': 'Sous-total',
      'discount': 'Remise',
      'tax': 'Taxe',
      'fee': 'Frais',
      'commission': 'Commission',
      'settlement': 'Règlement',
      'transaction': 'Transaction',
      'amount': 'Montant',
      'currency': 'Devise',
      'status': 'Statut',
      'pending': 'En Attente',
      'processing': 'En Cours',
      'completed': 'Terminé',
      'failed': 'Échoué',
      'refunded': 'Remboursé',
      'cancelled': 'Annulé',
      'expired': 'Expiré',
      'active': 'Actif',
      'inactive': 'Inactif',
      'locked': 'Verrouillé',
      'unlocked': 'Déverrouillé',
      'verified': 'Vérifié',
      'unverified': 'Non Vérifié',
      'bind': 'Lier',
      'unbind': 'Délier',
      'upgrade': 'Améliorer',
      'downgrade': 'Rétrograder',
      'renew': 'Renouveler',
      'expire': 'Expirer',
      'vip': 'VIP',
      'premium': 'Premium',
      'free': 'Gratuit',
      'paid': 'Payant',
      'trial': 'Essai',
      'new': 'Nouveau',
      'hot': 'Hot',
      'recommend': 'Recommander',
      'popular': 'Populaire',
      'latest': 'Dernier',
      'oldest': 'Plus Ancien',
      'price': 'Prix',
      'quantity': 'Quantité',
      'total_price': 'Prix Total',
      'unit_price': 'Prix Unitaire',
      'description': 'Description',
      'content': 'Contenu',
      'title': 'Titre',
      'summary': 'Résumé',
      'detail': 'Détail',
      'category': 'Catégorie',
      'tag': 'Tag',
      'type': 'Type',
      'date': 'Date',
      'time': 'Temps',
      'duration': 'Durée',
      'created_at': 'Créé le',
      'updated_at': 'Mis à jour le',
      'expired_at': 'Expire le',
      'view': 'Voir',
      'browse': 'Parcourir',
      'read': 'Lire',
      'write': 'Écrire',
      'share': 'Partager',
      'download': 'Télécharger',
      'upload': 'Téléverser',
      'export': 'Exporter',
      'import': 'Importer',
      'sync': 'Synchroniser',
      'refresh': 'Actualiser',
      'update': 'Mettre à jour',
      'delete_confirm': 'Êtes-vous sûr de vouloir supprimer?',
      'save_success': 'Enregistré avec Succès',
      'save_failed': 'Échec de l\'Enregistrement',
      'operation_success': 'Opération Réussie',
      'operation_failed': 'Opération Échouée',
      'network_error': 'Erreur Réseau',
      'system_error': 'Erreur Système',
      'permission_denied': 'Permission Refusée',
      'session_expired': 'Session Expirée',
      'please_login': 'Veuillez vous connecter',
      'copyright': 'Droits d\'Auteur',
      'terms_of_service': 'Conditions d\'Utilisation',
      'privacy_policy': 'Politique de Confidentialité',
      'contact_us': 'Nous Contacter',
      'about_us': 'À Propos',
      'help_center': 'Centre d\'Aide',
      'faq': 'FAQ',
      'feedback': 'Commentaires',
      'report': 'Signaler',
      'intelligent_acupuncture': 'Acupuncture Intelligente',
      'select_symptoms': 'Sélectionner les Symptômes',
      'select_body_region': 'Sélectionner la Zone Touchée',
      'tongue_diagnosis': 'Diagnostic de la Langue',
      'pulse_diagnosis': 'Diagnostic du Pouls',
      'diagnosis_result': 'Résultat du Diagnostic',
      'treatment_principle': 'Principe de Traitement',
      'treatment_strategy': 'Stratégie de Traitement',
      'prescription': 'Prescription',
      'main_points': 'Points Principaux',
      'paired_points': 'Points Associés',
      'dong_points': 'Points Extraordinaires Dong',
      'nihaixia_points': 'Points Spéciaux Ni Haixia',
      'traditional_points': 'Méridiens Traditionnels',
      'needle_depth': 'Profondeur de l\'Aiguille',
      'needle_angle': 'Angle de l\'Aiguille',
      'manipulation': 'Manipulation',
      'reinforcement_reduction': 'Renforcement/Drainage',
      'indication': 'Indication',
      'location': 'Localisation',
      'contraindication': 'Contre-indication',
      'operation_notes': 'Notes d\'Opération',
      'acupoint_source': 'Source du Point',
      'source_reference': 'Référence de la Source',
      'clinical_note': 'Note Clinique',
      'prescription_principle': 'Principe de Sélection',
      'body_layers': 'Couches d\'Affichage',
      'all_layers': 'Tout',
      'bone_layer': 'Os',
      'muscle_layer': 'Muscle',
      'meridian_layer': 'Méridien',
    },
      'app_name': 'Academia Lingji',
      'platform_slogan': 'Promoviendo la Cultura Tradicional · Heredando la Sabiduría Nacional',
      'platform_description': 'Plataforma de Intercambio Académico de Cultura Tradicional China',
      'home': 'Inicio',
      'tcm': 'Medicina China',
      'acupuncture': 'Acupuntura',
      'fortune': 'Destino',
      'wuyun': 'Wu Yun',
      'blog': 'Blog',
      'store': 'Tienda',
      'promotion': 'Promoción',
      'community': 'Comunidad',
      'my': 'Mi',
      'login': 'Iniciar Sesión',
      'register': 'Registrarse',
      'logout': 'Cerrar Sesión',
      'member': 'Miembro',
      'settings': 'Configuración',
      'profile': 'Perfil',
      'wallet': 'Billetera',
      'lingji_balance': 'Saldo Lingji',
      'member_level': 'Nivel de Miembro',
      'free_member': 'Miembro Gratis',
      'basic_member': 'Miembro Básico',
      'standard_member': 'Miembro Estándar',
      'premium_member': 'Miembro Premium',
      'ultimate_member': 'Miembro Supremo',
      'gold_member': 'Miembro Oro',
      'verification': 'Verificación',
      'email_verification': 'Verificación de Email',
      'phone_verification': 'Verificación de Teléfono',
      'face_verification': 'Verificación Facial',
      'verified': 'Verificado',
      'not_verified': 'No Verificado',
      'change_password': 'Cambiar Contraseña',
      'disclaimer': 'Aviso Legal',
      'payment_info': 'WeChat Pay y Alipay soportados',
      'settlement_info': 'Fondos liquidados y retenidos en Hong Kong',
      'promotion_rules': 'Registro gratuito, comisión solo en transacciones reales',
      'level1_commission': 'Comisión Nivel 1',
      'level2_commission': 'Comisión Nivel 2',
      'talent_showcase': 'Vitrina de Talentos',
      'affiliate_center': 'Centro de Afiliados',
      'share_link': 'Enlace para Compartir',
      'qr_code': 'Código QR',
      'server_region': 'Hong Kong',
      'payment': 'Pago',
      'payment_method': 'Método de Pago',
      'recharge': 'Recargar',
      'withdraw': 'Retirar',
      'order_history': 'Historial de Pedidos',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'confirm': 'Confirmar',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'edit': 'Editar',
      'delete': 'Eliminar',
      'search': 'Buscar',
      'loading': 'Cargando',
      'error': 'Error',
      'success': 'Éxito',
      'warning': 'Advertencia',
      'info': 'Info',
      'yes': 'Sí',
      'no': 'No',
      'ok': 'OK',
      'back': 'Volver',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'submit': 'Enviar',
      'reset': 'Restablecer',
      'close': 'Cerrar',
      'open': 'Abrir',
      'enable': 'Habilitar',
      'disable': 'Deshabilitar',
      'enabled': 'Habilitado',
      'disabled': 'Deshabilitado',
      'all': 'Todo',
      'none': 'Ninguno',
      'required': 'Requerido',
      'optional': 'Opcional',
      'username': 'Nombre de usuario',
      'password': 'Contraseña',
      'email': 'Email',
      'phone': 'Teléfono',
      'captcha': 'Captcha',
      'send_code': 'Enviar Código',
      'balance': 'Saldo',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'discount': 'Descuento',
      'tax': 'Impuesto',
      'fee': 'Tarifa',
      'commission': 'Comisión',
      'settlement': 'Liquidación',
      'transaction': 'Transacción',
      'amount': 'Monto',
      'currency': 'Moneda',
      'status': 'Estado',
      'pending': 'Pendiente',
      'processing': 'Procesando',
      'completed': 'Completado',
      'failed': 'Fallido',
      'refunded': 'Reembolsado',
      'cancelled': 'Cancelado',
      'expired': 'Expirado',
      'active': 'Activo',
      'inactive': 'Inactivo',
      'locked': 'Bloqueado',
      'unlocked': 'Desbloqueado',
      'verified': 'Verificado',
      'unverified': 'No Verificado',
      'bind': 'Vincular',
      'unbind': 'Desvincular',
      'upgrade': 'Mejorar',
      'downgrade': 'Degradar',
      'renew': 'Renovar',
      'expire': 'Expirar',
      'vip': 'VIP',
      'premium': 'Premium',
      'free': 'Gratis',
      'paid': 'De Pago',
      'trial': 'Prueba',
      'new': 'Nuevo',
      'hot': 'Hot',
      'recommend': 'Recomendar',
      'popular': 'Popular',
      'latest': 'Último',
      'oldest': 'Más Antiguo',
      'price': 'Precio',
      'quantity': 'Cantidad',
      'total_price': 'Precio Total',
      'unit_price': 'Precio Unitario',
      'description': 'Descripción',
      'content': 'Contenido',
      'title': 'Título',
      'summary': 'Resumen',
      'detail': 'Detalle',
      'category': 'Categoría',
      'tag': 'Etiqueta',
      'type': 'Tipo',
      'date': 'Fecha',
      'time': 'Hora',
      'duration': 'Duración',
      'created_at': 'Creado el',
      'updated_at': 'Actualizado el',
      'expired_at': 'Expira el',
      'view': 'Ver',
      'browse': 'Explorar',
      'read': 'Leer',
      'write': 'Escribir',
      'share': 'Compartir',
      'download': 'Descargar',
      'upload': 'Subir',
      'export': 'Exportar',
      'import': 'Importar',
      'sync': 'Sincronizar',
      'refresh': 'Actualizar',
      'update': 'Actualizar',
      'delete_confirm': '¿Está seguro de que desea eliminar?',
      'save_success': 'Guardado Exitosamente',
      'save_failed': 'Error al Guardar',
      'operation_success': 'Operación Exitosa',
      'operation_failed': 'Operación Fallida',
      'network_error': 'Error de Red',
      'system_error': 'Error del Sistema',
      'permission_denied': 'Permiso Denegado',
      'session_expired': 'Sesión Expirada',
      'please_login': 'Por favor inicie sesión',
      'copyright': 'Derechos de Autor',
      'terms_of_service': 'Términos de Servicio',
      'privacy_policy': 'Política de Privacidad',
      'contact_us': 'Contáctenos',
      'about_us': 'Sobre Nosotros',
      'help_center': 'Centro de Ayuda',
      'faq': 'FAQ',
      'feedback': 'Comentarios',
      'report': 'Reportar',
      'intelligent_acupuncture': 'Acupuntura Inteligente',
      'select_symptoms': 'Seleccionar Síntomas',
      'select_body_region': 'Seleccionar Área Afectada',
      'tongue_diagnosis': 'Diagnóstico de Lengua',
      'pulse_diagnosis': 'Diagnóstico de Pulso',
      'diagnosis_result': 'Resultado del Diagnóstico',
      'treatment_principle': 'Principio de Tratamiento',
      'treatment_strategy': 'Estrategia de Tratamiento',
      'prescription': 'Prescripción',
      'main_points': 'Puntos Principales',
      'paired_points': 'Puntos Pareados',
      'dong_points': 'Puntos Extraordinarios Dong',
      'nihaixia_points': 'Puntos Especiales Ni Haixia',
      'traditional_points': 'Meridianos Tradicionales',
      'needle_depth': 'Profundidad de Aguja',
      'needle_angle': 'Ángulo de Aguja',
      'manipulation': 'Manipulación',
      'reinforcement_reduction': 'Tonificación/Drenaje',
      'indication': 'Indicación',
      'location': 'Localización',
      'contraindication': 'Contraindicación',
      'operation_notes': 'Notas de Operación',
      'acupoint_source': 'Fuente del Punto',
      'source_reference': 'Referencia de Fuente',
      'clinical_note': 'Nota Clínica',
      'prescription_principle': 'Principio de Selección',
      'body_layers': 'Capas de Visualización',
      'all_layers': 'Todo',
      'bone_layer': 'Hueso',
      'muscle_layer': 'Músculo',
      'meridian_layer': 'Meridiano',
    },
      'app_name': 'Академия Линцзи',
      'platform_slogan': 'Продвижение традиционной культуры · Сохранение национальной мудрости',
      'platform_description': 'Платформа академического обмена традиционной китайской культурой',
      'home': 'Главная',
      'tcm': 'Китайская медицина',
      'acupuncture': 'Иглоукалывание',
      'fortune': 'Судьба',
      'wuyun': 'У Юнь',
      'blog': 'Блог',
      'store': 'Магазин',
      'promotion': 'Продвижение',
      'community': 'Сообщество',
      'my': 'Мой',
      'login': 'Вход',
      'register': 'Регистрация',
      'logout': 'Выход',
      'member': 'Участник',
      'settings': 'Настройки',
      'profile': 'Профиль',
      'wallet': 'Кошелёк',
      'lingji_balance': 'Баланс Линцзи',
      'member_level': 'Уровень участника',
      'free_member': 'Бесплатный участник',
      'basic_member': 'Базовый участник',
      'standard_member': 'Стандартный участник',
      'premium_member': 'Премиум участник',
      'ultimate_member': 'Максимальный участник',
      'gold_member': 'Золотой участник',
      'verification': 'Верификация',
      'email_verification': 'Верификация Email',
      'phone_verification': 'Верификация телефона',
      'face_verification': 'Верификация лица',
      'verified': 'Верифицирован',
      'not_verified': 'Не верифицирован',
      'change_password': 'Изменить пароль',
      'disclaimer': 'Отказ от ответственности',
      'payment_info': 'WeChat Pay и Alipay поддерживаются',
      'settlement_info': 'Средства хранятся в Гонконге',
      'promotion_rules': 'Бесплатная регистрация, комиссия только с реальных транзакций',
      'level1_commission': 'Комиссия 1 уровня',
      'level2_commission': 'Комиссия 2 уровня',
      'talent_showcase': 'Витрина талантов',
      'affiliate_center': 'Партнёрский центр',
      'share_link': 'Ссылка для шаринга',
      'qr_code': 'QR-код',
      'server_region': 'Гонконг',
      'payment': 'Оплата',
      'payment_method': 'Способ оплаты',
      'recharge': 'Пополнение',
      'withdraw': 'Вывод',
      'order_history': 'История заказов',
      'language': 'Язык',
      'select_language': 'Выбрать язык',
      'confirm': 'Подтвердить',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'edit': 'Редактировать',
      'delete': 'Удалить',
      'search': 'Поиск',
      'loading': 'Загрузка',
      'error': 'Ошибка',
      'success': 'Успешно',
      'warning': 'Предупреждение',
      'info': 'Информация',
      'yes': 'Да',
      'no': 'Нет',
      'ok': 'OK',
      'back': 'Назад',
      'next': 'Далее',
      'previous': 'Предыдущий',
      'submit': 'Отправить',
      'reset': 'Сбросить',
      'close': 'Закрыть',
      'open': 'Открыть',
      'enable': 'Включить',
      'disable': 'Выключить',
      'enabled': 'Включено',
      'disabled': 'Выключено',
      'all': 'Все',
      'none': 'Нет',
      'required': 'Обязательно',
      'optional': 'Необязательно',
      'username': 'Имя пользователя',
      'password': 'Пароль',
      'email': 'Email',
      'phone': 'Телефон',
      'captcha': 'Капча',
      'send_code': 'Отправить код',
      'balance': 'Баланс',
      'total': 'Итого',
      'subtotal': 'Подитог',
      'discount': 'Скидка',
      'tax': 'Налог',
      'fee': 'Комиссия',
      'commission': 'Комиссия',
      'settlement': 'Расчёт',
      'transaction': 'Транзакция',
      'amount': 'Сумма',
      'currency': 'Валюта',
      'status': 'Статус',
      'pending': 'В ожидании',
      'processing': 'Обработка',
      'completed': 'Завершено',
      'failed': 'Неудачно',
      'refunded': 'Возврат',
      'cancelled': 'Отменено',
      'expired': 'Истекло',
      'active': 'Активно',
      'inactive': 'Неактивно',
      'locked': 'Заблокировано',
      'unlocked': 'Разблокировано',
      'verified': 'Верифицировано',
      'unverified': 'Не верифицировано',
      'bind': 'Привязать',
      'unbind': 'Отвязать',
      'upgrade': 'Улучшить',
      'downgrade': 'Понизить',
      'renew': 'Продлить',
      'expire': 'Истечь',
      'vip': 'VIP',
      'premium': 'Премиум',
      'free': 'Бесплатно',
      'paid': 'Платно',
      'trial': 'Пробный',
      'new': 'Новое',
      'hot': 'Горячее',
      'recommend': 'Рекомендовать',
      'popular': 'Популярное',
      'latest': 'Последнее',
      'oldest': 'Самое старое',
      'price': 'Цена',
      'quantity': 'Количество',
      'total_price': 'Общая цена',
      'unit_price': 'Цена за единицу',
      'description': 'Описание',
      'content': 'Содержание',
      'title': 'Заголовок',
      'summary': 'Резюме',
      'detail': 'Подробности',
      'category': 'Категория',
      'tag': 'Тег',
      'type': 'Тип',
      'date': 'Дата',
      'time': 'Время',
      'duration': 'Продолжительность',
      'created_at': 'Создано',
      'updated_at': 'Обновлено',
      'expired_at': 'Истекает',
      'view': 'Просмотр',
      'browse': 'Обзор',
      'read': 'Читать',
      'write': 'Писать',
      'share': 'Поделиться',
      'download': 'Скачать',
      'upload': 'Загрузить',
      'export': 'Экспорт',
      'import': 'Импорт',
      'sync': 'Синхронизация',
      'refresh': 'Обновить',
      'update': 'Обновление',
      'delete_confirm': 'Вы уверены, что хотите удалить?',
      'save_success': 'Успешно сохранено',
      'save_failed': 'Ошибка сохранения',
      'operation_success': 'Операция успешна',
      'operation_failed': 'Операция не удалась',
      'network_error': 'Ошибка сети',
      'system_error': 'Системная ошибка',
      'permission_denied': 'Доступ запрещён',
      'session_expired': 'Сессия истекла',
      'please_login': 'Пожалуйста, войдите',
      'copyright': 'Авторские права',
      'terms_of_service': 'Условия использования',
      'privacy_policy': 'Политика конфиденциальности',
      'contact_us': 'Связаться с нами',
      'about_us': 'О нас',
      'help_center': 'Центр помощи',
      'faq': 'FAQ',
      'feedback': 'Отзывы',
      'report': 'Пожаловаться',
      'intelligent_acupuncture': 'Интеллектуальное иглоукалывание',
      'select_symptoms': 'Выбрать симптомы',
      'select_body_region': 'Выбрать поражённую область',
      'tongue_diagnosis': 'Диагностика по языку',
      'pulse_diagnosis': 'Диагностика по пульсу',
      'diagnosis_result': 'Результат диагностики',
      'treatment_principle': 'Принцип лечения',
      'treatment_strategy': 'Стратегия лечения',
      'prescription': 'Рецепт',
      'main_points': 'Основные точки',
      'paired_points': 'Парные точки',
      'dong_points': 'Точки Дун',
      'nihaixia_points': 'Специальные точки Ни Хайся',
      'traditional_points': 'Традиционные меридианы',
      'needle_depth': 'Глубина укола',
      'needle_angle': 'Угол укола',
      'manipulation': 'Манипуляция',
      'reinforcement_reduction': 'Тонизация/Дренаж',
      'indication': 'Показание',
      'location': 'Локализация',
      'contraindication': 'Противопоказание',
      'operation_notes': 'Заметки по операции',
      'acupoint_source': 'Источник точки',
      'source_reference': 'Справочный источник',
      'clinical_note': 'Клиническая заметка',
      'prescription_principle': 'Принцип подбора',
      'body_layers': 'Слои отображения',
      'all_layers': 'Все',
      'bone_layer': 'Кость',
      'muscle_layer': 'Мышца',
      'meridian_layer': 'Меридиан',
    },
      'app_name': 'أكاديمية لينغجي',
      'platform_slogan': 'تعزيز الثقافة التقليدية · وراثة الحكمة الوطنية',
      'platform_description': 'منصة التبادل الأكاديمي للثقافة الصينية التقليدية',
      'home': 'الرئيسية',
      'tcm': 'الطب الصيني',
      'acupuncture': 'الوخز بالإبر',
      'fortune': 'المصير',
      'wuyun': 'وو يون',
      'blog': 'المدونة',
      'store': 'المتجر',
      'promotion': 'الترويج',
      'community': 'المجتمع',
      'my': 'حسابي',
      'login': 'تسجيل الدخول',
      'register': 'التسجيل',
      'logout': 'تسجيل الخروج',
      'member': 'العضو',
      'settings': 'الإعدادات',
      'profile': 'الملف الشخصي',
      'wallet': 'المحفظة',
      'lingji_balance': 'رصيد لينغجي',
      'member_level': 'مستوى العضوية',
      'free_member': 'عضو مجاني',
      'basic_member': 'عضو أساسي',
      'standard_member': 'عضو قياسي',
      'premium_member': 'عضو مميز',
      'ultimate_member': 'عضو متميز',
      'gold_member': 'عضو ذهبي',
      'verification': 'التحقق',
      'email_verification': 'التحقق من البريد الإلكتروني',
      'phone_verification': 'التحقق من الهاتف',
      'face_verification': 'التحقق من الوجه',
      'verified': 'تم التحقق',
      'not_verified': 'غير محقق',
      'change_password': 'تغيير كلمة المرور',
      'disclaimer': 'إخلاء المسؤولية',
      'payment_info': 'دعم WeChat Pay و Alipay',
      'settlement_info': 'الأموال ت settling في هونغ كونغ',
      'promotion_rules': 'تسجيل مجاني، عمولة على المعاملات الحقيقية فقط',
      'level1_commission': 'عمولة المستوى الأول',
      'level2_commission': 'عمولة المستوى الثاني',
      'talent_showcase': 'عرض المواهب',
      'affiliate_center': 'مركز التسويق بالعمولة',
      'share_link': 'رابط المشاركة',
      'qr_code': 'رمز QR',
      'server_region': 'هونغ كونغ',
      'payment': 'الدفع',
      'payment_method': 'طريقة الدفع',
      'recharge': 'الشحن',
      'withdraw': 'السحب',
      'order_history': 'سجل الطلبات',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'edit': 'تعديل',
      'delete': 'حذف',
      'search': 'بحث',
      'loading': 'جاري التحميل',
      'error': 'خطأ',
      'success': 'نجاح',
      'warning': 'تحذير',
      'info': 'معلومات',
      'yes': 'نعم',
      'no': 'لا',
      'ok': 'موافق',
      'back': 'رجوع',
      'next': 'التالي',
      'previous': 'السابق',
      'submit': 'إرسال',
      'reset': 'إعادة تعيين',
      'close': 'إغلاق',
      'open': 'فتح',
      'enable': 'تفعيل',
      'disable': 'تعطيل',
      'enabled': 'مفعّل',
      'disabled': 'معطّل',
      'all': 'الكل',
      'none': 'لا شيء',
      'required': 'مطلوب',
      'optional': 'اختياري',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'captcha': 'كابتشا',
      'send_code': 'إرسال الرمز',
      'balance': 'الرصيد',
      'total': 'المجموع',
      'subtotal': 'المجموع الفرعي',
      'discount': 'خصم',
      'tax': 'ضريبة',
      'fee': 'رسوم',
      'commission': 'عمولة',
      'settlement': 'تسوية',
      'transaction': 'معاملة',
      'amount': 'المبلغ',
      'currency': 'العملة',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'processing': 'قيد المعالجة',
      'completed': 'مكتمل',
      'failed': 'فشل',
      'refunded': 'تم الاسترداد',
      'cancelled': 'ملغى',
      'expired': 'منتهي الصلاحية',
      'active': 'نشط',
      'inactive': 'غير نشط',
      'locked': 'مقفل',
      'unlocked': 'مفتوح',
      'verified': 'محقق',
      'unverified': 'غير محقق',
      'bind': 'ربط',
      'unbind': 'إلغاء الربط',
      'upgrade': 'ترقية',
      'downgrade': 'تخفيض',
      'renew': 'تجديد',
      'expire': 'انتهاء',
      'vip': 'VIP',
      'premium': 'مميز',
      'free': 'مجاني',
      'paid': 'مدفوع',
      'trial': 'تجريبي',
      'new': 'جديد',
      'hot': 'ساخن',
      'recommend': 'موصى به',
      'popular': 'شائع',
      'latest': 'الأحدث',
      'oldest': 'الأقدم',
      'price': 'السعر',
      'quantity': 'الكمية',
      'total_price': 'السعر الإجمالي',
      'unit_price': 'سعر الوحدة',
      'description': 'الوصف',
      'content': 'المحتوى',
      'title': 'العنوان',
      'summary': 'ملخص',
      'detail': 'التفاصيل',
      'category': 'الفئة',
      'tag': 'الوسم',
      'type': 'النوع',
      'date': 'التاريخ',
      'time': 'الوقت',
      'duration': 'المدة',
      'created_at': 'تاريخ الإنشاء',
      'updated_at': 'تاريخ التحديث',
      'expired_at': 'تاريخ الانتهاء',
      'view': 'عرض',
      'browse': 'تصفح',
      'read': 'قراءة',
      'write': 'كتابة',
      'share': 'مشاركة',
      'download': 'تحميل',
      'upload': 'رفع',
      'export': 'تصدير',
      'import': 'استيراد',
      'sync': 'مزامنة',
      'refresh': 'تحديث',
      'update': 'تحديث',
      'delete_confirm': 'هل أنت متأكد من الحذف؟',
      'save_success': 'تم الحفظ بنجاح',
      'save_failed': 'فشل الحفظ',
      'operation_success': 'تمت العملية بنجاح',
      'operation_failed': 'فشلت العملية',
      'network_error': 'خطأ في الشبكة',
      'system_error': 'خطأ في النظام',
      'permission_denied': 'تم رفض الإذن',
      'session_expired': 'انتهت الجلسة',
      'please_login': 'الرجاء تسجيل الدخول أولاً',
      'copyright': 'حقوق النشر',
      'terms_of_service': 'شروط الخدمة',
      'privacy_policy': 'سياسة الخصوصية',
      'contact_us': 'اتصل بنا',
      'about_us': 'من نحن',
      'help_center': 'مركز المساعدة',
      'faq': 'الأسئلة الشائعة',
      'feedback': 'ملاحظات',
      'report': 'إبلاغ',
      'intelligent_acupuncture': 'الوخز بالإبر الذكي',
      'select_symptoms': 'اختر الأعراض',
      'select_body_region': 'اختر المنطقة المصابة',
      'tongue_diagnosis': 'تشخيص اللسان',
      'pulse_diagnosis': 'تشخيص النبض',
      'diagnosis_result': 'نتيجة التشخيص',
      'treatment_principle': 'مبدأ العلاج',
      'treatment_strategy': 'استراتيجية العلاج',
      'prescription': 'الوصفة الطبية',
      'main_points': 'النقاط الرئيسية',
      'paired_points': 'النقاط المقترنة',
      'dong_points': 'نقاط دون الاستثنائية',
      'nihaixia_points': 'نقاط نى هاي شييا الخاصة',
      'traditional_points': 'الزوال التقليدي',
      'needle_depth': 'عمق الإبرة',
      'needle_angle': 'زاوية الإبرة',
      'manipulation': 'التلاعب',
      'reinforcement_reduction': 'التعزيز/التصريف',
      'indication': 'دواعي الاستعمال',
      'location': 'الموقع',
      'contraindication': 'موانع الاستعمال',
      'operation_notes': 'ملاحظات التشغيل',
      'acupoint_source': 'مصدر النقطة',
      'source_reference': 'المرجع',
      'clinical_note': 'ملاحظة سريرية',
      'prescription_principle': 'مبدأ الوصفة',
      'body_layers': 'طبقات العرض',
      'all_layers': 'الكل',
      'bone_layer': 'العظم',
      'muscle_layer': 'العضلة',
      'meridian_layer': 'الزوال',
    },
  };
}

extension LocaleExtension on Locale {
  String get displayName {
    switch ('${languageCode}_${countryCode ?? 'TW'}') {
      case 'zh_TW': return '繁體中文';
      case 'zh_CN': return '簡體中文';
      case 'en_US': return 'English';
      case 'fr_FR': return 'Français';
      case 'es_ES': return 'Español';
      case 'ru_RU': return 'Русский';
      case 'ar_SA': return 'العربية';
      default: return '$languageCode ($countryCode)';
    }
  }
}
